services:
  backend:
    build:
      context: ./backend  # Cambia el contexto al directorio del backend
      dockerfile: Dockerfile  # El Dockerfile est치 en la misma carpeta
    volumes:
      - ./backend:/app  # Mapea el c칩digo local al contenedor
    ports:
      - "5001:5001"

  frontend:
    build:
      context: ./frontend  # Cambia el contexto al directorio del frontend
      dockerfile: Dockerfile  # El Dockerfile est치 en la misma carpeta
    volumes:
      - ./frontend:/app  # Mapea el c칩digo local al contenedor
    ports:
      - "5000:5000"
